//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Data.Entity;
using System.Data.Entity.Infrastructure;

public partial class GymDBEntities : DbContext
{
    public GymDBEntities()
        : base("name=GymDBEntities")
    {
    }

    protected override void OnModelCreating(DbModelBuilder modelBuilder)
    {
        throw new UnintentionalCodeFirstException();
    }

    public virtual DbSet<Cart> Cart { get; set; }
    public virtual DbSet<Product> Product { get; set; }
    public virtual DbSet<ProductTypes> ProductTypes { get; set; }
    public virtual DbSet<Userinfo> Userinfo { get; set; }
}
